apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      volumes:
      - name: gitea-ps
        persistentVolumeClaim:
          claimName: gitea-pv-claim
      containers:
      - name: gitea
        image: gitea/gitea:1.11.3
        ports:
        - containerPort: 22
          name: ssh
        - containerPort: 3000
          name: web
        resources:
          requests:
            cpu: 1
            memory: 512Mi
          limits:
            cpu: 2
            memory: 1Gi
        volumeMounts:
        - name: gitea-ps
          mountPath: /data
        env:
        - name: LOCAL_ROOT_URL
          value: "http://kube30:32642/"
        - name: ROOT_URL
          value: "http://kube30:32642/"
        - name: HTTP_ADDR
          value: "kube30"
        - name: SSH_DOMAIN
          value: "kube30"
        - name: SSH_PORT
          value: "30101"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pv-claim
  labels:
    app: gitea
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: gitea
  labels:
    app: gitea
spec:
  ports:
  - port: 22
    name: ssh 
    nodePort: 30101
  - port: 3000
    name: web
    nodePort: 32642
  selector:
    app: gitea
  type: NodePort

# vim: set ts=2 sw=2
